### ISSUE TITLE
Feature - Push env variables to clouds / ci-cd platforms

### ISSUE THREAD

**Issue by mathix420** [mathix420/pylone#5]
Maybe an integration like this

```yaml
env:
    - gitlab:
        API_KEY: !env API_KEY
```
