### ISSUE TITLE
Add !doppler YAML tag to automatically import all doppler env variables

### ISSUE THREAD

**Issue by mathix420** [mathix420/pylone#9]
Proposed usage:

```yaml
environ: !doppler
```

```yaml
environ:
    _: !doppler
    OTHER_KEY: OTHER_VALUE
```
